# -*- coding: utf-8 -*-
"""Data Structure-Hash map

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10w5EQzGMXWivoRNmpOFVCuH_hKcbczhk
"""

def get_hash(key) :
  h = 0
  for char in key :
    h += ord(char)
  return h%100

get_hash('march 6')

class HashTable :
  def __init__(self) :
    self.MAX = 100
    self.arr = [[] for i in range(self.MAX)]
    
  def get_hash(self, key) :
    h = 0
    for char in key :
      h += ord(char)
    return h % self.MAX

  def __setitem__(self , key , val) :
    h = get_hash(key)
    found = False
    for idx , element in enumerate(self.arr[h]) :
      if len(element) == 2 and element[0] == key :
        self.arr[h][idx] = (key,val)
        found = True
        break
    if not found :
        self.arr[h].append((key , val)) 

  def __getitem__(self , key) :
    h = get_hash(key)
    return self.arr[h]

  def __delitem__(self , key) :
    h = get_hash(key)
    self.arr[h] = None

t = HashTable()

t['march 6'] =130
t['march 17'] = 459

t['march 17']

t.arr